// Pure data module for the composer's emoji picker and `:shortcode:` autocomplete.
// No imports — keep it dependency-free so it can be consumed anywhere.

export interface EmojiEntry {
  char: string
  name: string
  keywords: string
  group: string
}

export interface EmojiShortcode {
  code: string
  char: string
}

/** Curated emoji set (~120) grouped into a few categories for the picker grid. */
export const EMOJI: EmojiEntry[] = [
  // ── Smileys（表情）─────────────────────────────
  { char: '😀', name: 'grinning', keywords: 'smile happy 笑 开心', group: 'smileys' },
  { char: '😃', name: 'smiley', keywords: 'happy joy 高兴', group: 'smileys' },
  { char: '😄', name: 'smile', keywords: 'happy laugh 大笑', group: 'smileys' },
  { char: '😁', name: 'grin', keywords: 'smile 咧嘴', group: 'smileys' },
  { char: '😆', name: 'laughing', keywords: 'lol haha 大笑', group: 'smileys' },
  { char: '😅', name: 'sweat_smile', keywords: 'phew 尴尬 苦笑', group: 'smileys' },
  { char: '🤣', name: 'rofl', keywords: 'lol rolling 笑翻', group: 'smileys' },
  { char: '😂', name: 'joy', keywords: 'lol tears 笑哭', group: 'smileys' },
  { char: '🙂', name: 'slight_smile', keywords: 'smile 微笑', group: 'smileys' },
  { char: '🙃', name: 'upside_down', keywords: 'silly 倒脸', group: 'smileys' },
  { char: '😉', name: 'wink', keywords: 'flirt 眨眼', group: 'smileys' },
  { char: '😊', name: 'blush', keywords: 'smile shy 害羞', group: 'smileys' },
  { char: '😇', name: 'innocent', keywords: 'angel 天使', group: 'smileys' },
  { char: '🥰', name: 'smiling_face_with_hearts', keywords: 'love adore 爱', group: 'smileys' },
  { char: '😍', name: 'heart_eyes', keywords: 'love crush 花痴', group: 'smileys' },
  { char: '🤩', name: 'star_struck', keywords: 'wow amazed 星星眼', group: 'smileys' },
  { char: '😘', name: 'kissing_heart', keywords: 'kiss love 飞吻', group: 'smileys' },
  { char: '😋', name: 'yum', keywords: 'tasty delicious 好吃', group: 'smileys' },
  { char: '😛', name: 'stuck_out_tongue', keywords: 'tongue 吐舌', group: 'smileys' },
  { char: '😜', name: 'stuck_out_tongue_winking_eye', keywords: 'joke 调皮', group: 'smileys' },
  { char: '🤪', name: 'zany_face', keywords: 'crazy silly 疯', group: 'smileys' },
  { char: '🤗', name: 'hugs', keywords: 'hug 抱抱', group: 'smileys' },
  { char: '🤭', name: 'hand_over_mouth', keywords: 'giggle 偷笑', group: 'smileys' },
  { char: '🤫', name: 'shushing', keywords: 'quiet secret 嘘', group: 'smileys' },
  { char: '🤔', name: 'thinking', keywords: 'hmm consider 思考', group: 'smileys' },
  { char: '😐', name: 'neutral', keywords: 'meh 无表情', group: 'smileys' },
  { char: '😑', name: 'expressionless', keywords: 'blank 面无表情', group: 'smileys' },
  { char: '😏', name: 'smirk', keywords: 'smug 得意', group: 'smileys' },
  { char: '😒', name: 'unamused', keywords: 'meh 不爽', group: 'smileys' },
  { char: '🙄', name: 'roll_eyes', keywords: 'annoyed 翻白眼', group: 'smileys' },
  { char: '😬', name: 'grimacing', keywords: 'awkward 龇牙', group: 'smileys' },
  { char: '😌', name: 'relieved', keywords: 'calm 释然', group: 'smileys' },
  { char: '😔', name: 'pensive', keywords: 'sad 失落', group: 'smileys' },
  { char: '😴', name: 'sleeping', keywords: 'zzz tired 睡', group: 'smileys' },
  { char: '😷', name: 'mask', keywords: 'sick 口罩', group: 'smileys' },
  { char: '🥳', name: 'partying_face', keywords: 'celebrate party 庆祝', group: 'smileys' },
  { char: '😎', name: 'sunglasses', keywords: 'cool 酷', group: 'smileys' },
  { char: '🤓', name: 'nerd', keywords: 'geek 书呆子', group: 'smileys' },
  { char: '🥺', name: 'pleading', keywords: 'puppy beg 委屈', group: 'smileys' },
  { char: '😳', name: 'flushed', keywords: 'embarrassed 脸红', group: 'smileys' },
  { char: '😭', name: 'sob', keywords: 'cry sad 大哭', group: 'smileys' },
  { char: '😢', name: 'cry', keywords: 'sad tear 哭', group: 'smileys' },
  { char: '😤', name: 'triumph', keywords: 'proud angry 哼', group: 'smileys' },
  { char: '😠', name: 'angry', keywords: 'mad 生气', group: 'smileys' },
  { char: '😡', name: 'rage', keywords: 'mad furious 愤怒', group: 'smileys' },
  { char: '🤯', name: 'exploding_head', keywords: 'mind blown 震惊', group: 'smileys' },
  { char: '😱', name: 'scream', keywords: 'fear shock 尖叫', group: 'smileys' },
  { char: '🥱', name: 'yawning_face', keywords: 'bored tired 打哈欠', group: 'smileys' },

  // ── Gestures（手势）────────────────────────────
  { char: '👍', name: 'thumbsup', keywords: '+1 like good 赞', group: 'gestures' },
  { char: '👎', name: 'thumbsdown', keywords: '-1 dislike bad 踩', group: 'gestures' },
  { char: '👌', name: 'ok_hand', keywords: 'ok perfect 好的', group: 'gestures' },
  { char: '✌️', name: 'v', keywords: 'victory peace 胜利', group: 'gestures' },
  { char: '🤞', name: 'crossed_fingers', keywords: 'luck hope 祈祷', group: 'gestures' },
  { char: '🤟', name: 'love_you_gesture', keywords: 'love 爱你', group: 'gestures' },
  { char: '🤘', name: 'metal', keywords: 'rock 摇滚', group: 'gestures' },
  { char: '🤙', name: 'call_me_hand', keywords: 'call shaka 打电话', group: 'gestures' },
  { char: '👈', name: 'point_left', keywords: 'left 左', group: 'gestures' },
  { char: '👉', name: 'point_right', keywords: 'right 右', group: 'gestures' },
  { char: '👆', name: 'point_up_2', keywords: 'up 上', group: 'gestures' },
  { char: '👇', name: 'point_down', keywords: 'down 下', group: 'gestures' },
  { char: '✋', name: 'raised_hand', keywords: 'stop high five 手', group: 'gestures' },
  { char: '🖐️', name: 'raised_hand_with_fingers_splayed', keywords: 'hand 张开', group: 'gestures' },
  { char: '🖖', name: 'vulcan_salute', keywords: 'spock 瓦肯', group: 'gestures' },
  { char: '👋', name: 'wave', keywords: 'hello bye 挥手', group: 'gestures' },
  { char: '👏', name: 'clap', keywords: 'applause bravo 鼓掌', group: 'gestures' },
  { char: '🙌', name: 'raised_hands', keywords: 'praise hooray 欢呼', group: 'gestures' },
  { char: '🤲', name: 'palms_up_together', keywords: 'pray offer 双手', group: 'gestures' },
  { char: '🙏', name: 'pray', keywords: 'please thanks 拜托 感谢', group: 'gestures' },
  { char: '🤝', name: 'handshake', keywords: 'deal agree 握手', group: 'gestures' },
  { char: '💪', name: 'muscle', keywords: 'strong flex 肌肉 加油', group: 'gestures' },
  { char: '✍️', name: 'writing_hand', keywords: 'write 写字', group: 'gestures' },
  { char: '👊', name: 'facepunch', keywords: 'fist bump 拳', group: 'gestures' },
  { char: '✊', name: 'fist', keywords: 'power 拳头', group: 'gestures' },

  // ── Hearts（爱心）─────────────────────────────
  { char: '❤️', name: 'heart', keywords: 'love red 爱 心', group: 'hearts' },
  { char: '🧡', name: 'orange_heart', keywords: 'love 橙心', group: 'hearts' },
  { char: '💛', name: 'yellow_heart', keywords: 'love 黄心', group: 'hearts' },
  { char: '💚', name: 'green_heart', keywords: 'love 绿心', group: 'hearts' },
  { char: '💙', name: 'blue_heart', keywords: 'love 蓝心', group: 'hearts' },
  { char: '💜', name: 'purple_heart', keywords: 'love 紫心', group: 'hearts' },
  { char: '🖤', name: 'black_heart', keywords: 'love 黑心', group: 'hearts' },
  { char: '🤍', name: 'white_heart', keywords: 'love 白心', group: 'hearts' },
  { char: '🤎', name: 'brown_heart', keywords: 'love 棕心', group: 'hearts' },
  { char: '💔', name: 'broken_heart', keywords: 'sad breakup 心碎', group: 'hearts' },
  { char: '💕', name: 'two_hearts', keywords: 'love 两心', group: 'hearts' },
  { char: '💞', name: 'revolving_hearts', keywords: 'love 旋转', group: 'hearts' },
  { char: '💓', name: 'heartbeat', keywords: 'love 心跳', group: 'hearts' },
  { char: '💗', name: 'heartpulse', keywords: 'love 心动', group: 'hearts' },
  { char: '💖', name: 'sparkling_heart', keywords: 'love 闪亮', group: 'hearts' },
  { char: '💘', name: 'cupid', keywords: 'love arrow 丘比特', group: 'hearts' },
  { char: '💝', name: 'gift_heart', keywords: 'love gift 礼物心', group: 'hearts' },
  { char: '💯', name: '100', keywords: 'perfect score 满分', group: 'hearts' },

  // ── Objects（物件）────────────────────────────
  { char: '🔥', name: 'fire', keywords: 'lit hot 火 热', group: 'objects' },
  { char: '⭐', name: 'star', keywords: 'favorite 星', group: 'objects' },
  { char: '🌟', name: 'star2', keywords: 'glowing shine 亮星', group: 'objects' },
  { char: '✨', name: 'sparkles', keywords: 'shine new 闪', group: 'objects' },
  { char: '💫', name: 'dizzy', keywords: 'star 晕', group: 'objects' },
  { char: '💥', name: 'boom', keywords: 'explosion 爆炸', group: 'objects' },
  { char: '🎉', name: 'tada', keywords: 'party celebrate 庆祝 撒花', group: 'objects' },
  { char: '🎊', name: 'confetti_ball', keywords: 'party 彩球', group: 'objects' },
  { char: '🎈', name: 'balloon', keywords: 'party 气球', group: 'objects' },
  { char: '🎁', name: 'gift', keywords: 'present 礼物', group: 'objects' },
  { char: '🏆', name: 'trophy', keywords: 'win award 奖杯', group: 'objects' },
  { char: '🥇', name: 'first_place', keywords: 'gold win 金牌', group: 'objects' },
  { char: '💡', name: 'bulb', keywords: 'idea light 灯泡 想法', group: 'objects' },
  { char: '🔔', name: 'bell', keywords: 'notification 铃', group: 'objects' },
  { char: '📌', name: 'pushpin', keywords: 'pin note 图钉', group: 'objects' },
  { char: '📎', name: 'paperclip', keywords: 'attach 回形针', group: 'objects' },
  { char: '🔗', name: 'link', keywords: 'url chain 链接', group: 'objects' },
  { char: '📢', name: 'loudspeaker', keywords: 'announce 喇叭', group: 'objects' },
  { char: '💻', name: 'computer', keywords: 'laptop 电脑', group: 'objects' },
  { char: '📱', name: 'iphone', keywords: 'mobile phone 手机', group: 'objects' },
  { char: '💾', name: 'floppy_disk', keywords: 'save 保存', group: 'objects' },
  { char: '📦', name: 'package', keywords: 'box release 包裹', group: 'objects' },
  { char: '📝', name: 'memo', keywords: 'note write 笔记', group: 'objects' },
  { char: '🔍', name: 'mag', keywords: 'search find 搜索', group: 'objects' },
  { char: '🔒', name: 'lock', keywords: 'secure 锁', group: 'objects' },
  { char: '🔑', name: 'key', keywords: 'password 钥匙', group: 'objects' },
  { char: '⚙️', name: 'gear', keywords: 'settings config 设置', group: 'objects' },
  { char: '🔧', name: 'wrench', keywords: 'fix tool 扳手', group: 'objects' },
  { char: '🔨', name: 'hammer', keywords: 'build tool 锤子', group: 'objects' },
  { char: '🐛', name: 'bug', keywords: 'issue error 虫 缺陷', group: 'objects' },
  { char: '☕', name: 'coffee', keywords: 'drink 咖啡', group: 'objects' },
  { char: '🍺', name: 'beer', keywords: 'drink cheers 啤酒', group: 'objects' },
  { char: '🍕', name: 'pizza', keywords: 'food 披萨', group: 'objects' },
  { char: '🚀', name: 'rocket', keywords: 'launch boost ship 火箭 助推', group: 'objects' },

  // ── Symbols（符号）────────────────────────────
  { char: '✅', name: 'white_check_mark', keywords: 'done yes 对 完成', group: 'symbols' },
  { char: '✔️', name: 'heavy_check_mark', keywords: 'check yes 勾', group: 'symbols' },
  { char: '☑️', name: 'ballot_box_with_check', keywords: 'check todo 选中', group: 'symbols' },
  { char: '❌', name: 'x', keywords: 'no wrong 错', group: 'symbols' },
  { char: '⚠️', name: 'warning', keywords: 'caution 警告', group: 'symbols' },
  { char: '❓', name: 'question', keywords: 'help ask 问号', group: 'symbols' },
  { char: '❗', name: 'exclamation', keywords: 'important 感叹号', group: 'symbols' },
  { char: '➕', name: 'heavy_plus_sign', keywords: 'add plus 加', group: 'symbols' },
  { char: '➖', name: 'heavy_minus_sign', keywords: 'minus 减', group: 'symbols' },
  { char: '🚫', name: 'no_entry_sign', keywords: 'forbidden ban 禁止', group: 'symbols' },
  { char: '🆗', name: 'ok', keywords: 'okay 好', group: 'symbols' },
  { char: '🆕', name: 'new', keywords: 'fresh 新', group: 'symbols' },
  { char: '⏳', name: 'hourglass_flowing_sand', keywords: 'wait loading 沙漏', group: 'symbols' },
  { char: '♻️', name: 'recycle', keywords: 'reuse 循环', group: 'symbols' },
  { char: '🔴', name: 'red_circle', keywords: 'red status 红', group: 'symbols' },
  { char: '🟢', name: 'green_circle', keywords: 'green status 绿', group: 'symbols' },
  { char: '🔵', name: 'blue_circle', keywords: 'blue status 蓝', group: 'symbols' },
  { char: '🟡', name: 'yellow_circle', keywords: 'yellow status 黄', group: 'symbols' },
  { char: '🟠', name: 'orange_circle', keywords: 'orange status 橙', group: 'symbols' },
  { char: '🟣', name: 'purple_circle', keywords: 'purple status 紫', group: 'symbols' }
]

/** Shortcode → char map for the inline `:code:` autocomplete. */
export const EMOJI_SHORTCODES: EmojiShortcode[] = [
  { code: 'grinning', char: '😀' },
  { code: 'smiley', char: '😃' },
  { code: 'smile', char: '😄' },
  { code: 'grin', char: '😁' },
  { code: 'laughing', char: '😆' },
  { code: 'sweat_smile', char: '😅' },
  { code: 'rofl', char: '🤣' },
  { code: 'joy', char: '😂' },
  { code: 'slight_smile', char: '🙂' },
  { code: 'upside_down', char: '🙃' },
  { code: 'wink', char: '😉' },
  { code: 'blush', char: '😊' },
  { code: 'innocent', char: '😇' },
  { code: 'heart_eyes', char: '😍' },
  { code: 'star_struck', char: '🤩' },
  { code: 'kissing_heart', char: '😘' },
  { code: 'yum', char: '😋' },
  { code: 'stuck_out_tongue', char: '😛' },
  { code: 'zany_face', char: '🤪' },
  { code: 'hugs', char: '🤗' },
  { code: 'shushing', char: '🤫' },
  { code: 'thinking', char: '🤔' },
  { code: 'neutral', char: '😐' },
  { code: 'smirk', char: '😏' },
  { code: 'roll_eyes', char: '🙄' },
  { code: 'relieved', char: '😌' },
  { code: 'pensive', char: '😔' },
  { code: 'sleeping', char: '😴' },
  { code: 'mask', char: '😷' },
  { code: 'partying_face', char: '🥳' },
  { code: 'sunglasses', char: '😎' },
  { code: 'nerd', char: '🤓' },
  { code: 'pleading', char: '🥺' },
  { code: 'flushed', char: '😳' },
  { code: 'sob', char: '😭' },
  { code: 'cry', char: '😢' },
  { code: 'angry', char: '😠' },
  { code: 'rage', char: '😡' },
  { code: 'exploding_head', char: '🤯' },
  { code: 'scream', char: '😱' },
  { code: 'thumbsup', char: '👍' },
  { code: '+1', char: '👍' },
  { code: 'thumbsdown', char: '👎' },
  { code: '-1', char: '👎' },
  { code: 'ok_hand', char: '👌' },
  { code: 'v', char: '✌️' },
  { code: 'crossed_fingers', char: '🤞' },
  { code: 'metal', char: '🤘' },
  { code: 'call_me_hand', char: '🤙' },
  { code: 'point_left', char: '👈' },
  { code: 'point_right', char: '👉' },
  { code: 'point_up_2', char: '👆' },
  { code: 'point_down', char: '👇' },
  { code: 'raised_hand', char: '✋' },
  { code: 'vulcan_salute', char: '🖖' },
  { code: 'wave', char: '👋' },
  { code: 'clap', char: '👏' },
  { code: 'raised_hands', char: '🙌' },
  { code: 'pray', char: '🙏' },
  { code: 'handshake', char: '🤝' },
  { code: 'muscle', char: '💪' },
  { code: 'writing_hand', char: '✍️' },
  { code: 'facepunch', char: '👊' },
  { code: 'fist', char: '✊' },
  { code: 'heart', char: '❤️' },
  { code: 'orange_heart', char: '🧡' },
  { code: 'yellow_heart', char: '💛' },
  { code: 'green_heart', char: '💚' },
  { code: 'blue_heart', char: '💙' },
  { code: 'purple_heart', char: '💜' },
  { code: 'black_heart', char: '🖤' },
  { code: 'white_heart', char: '🤍' },
  { code: 'broken_heart', char: '💔' },
  { code: 'two_hearts', char: '💕' },
  { code: 'sparkling_heart', char: '💖' },
  { code: 'cupid', char: '💘' },
  { code: '100', char: '💯' },
  { code: 'fire', char: '🔥' },
  { code: 'star', char: '⭐' },
  { code: 'star2', char: '🌟' },
  { code: 'sparkles', char: '✨' },
  { code: 'dizzy', char: '💫' },
  { code: 'boom', char: '💥' },
  { code: 'tada', char: '🎉' },
  { code: 'confetti_ball', char: '🎊' },
  { code: 'balloon', char: '🎈' },
  { code: 'gift', char: '🎁' },
  { code: 'trophy', char: '🏆' },
  { code: 'first_place', char: '🥇' },
  { code: 'bulb', char: '💡' },
  { code: 'bell', char: '🔔' },
  { code: 'pushpin', char: '📌' },
  { code: 'paperclip', char: '📎' },
  { code: 'link', char: '🔗' },
  { code: 'loudspeaker', char: '📢' },
  { code: 'computer', char: '💻' },
  { code: 'iphone', char: '📱' },
  { code: 'floppy_disk', char: '💾' },
  { code: 'package', char: '📦' },
  { code: 'memo', char: '📝' },
  { code: 'mag', char: '🔍' },
  { code: 'lock', char: '🔒' },
  { code: 'key', char: '🔑' },
  { code: 'gear', char: '⚙️' },
  { code: 'wrench', char: '🔧' },
  { code: 'hammer', char: '🔨' },
  { code: 'bug', char: '🐛' },
  { code: 'coffee', char: '☕' },
  { code: 'beer', char: '🍺' },
  { code: 'pizza', char: '🍕' },
  { code: 'rocket', char: '🚀' },
  { code: 'white_check_mark', char: '✅' },
  { code: 'heavy_check_mark', char: '✔️' },
  { code: 'x', char: '❌' },
  { code: 'warning', char: '⚠️' },
  { code: 'question', char: '❓' },
  { code: 'exclamation', char: '❗' },
  { code: 'heavy_plus_sign', char: '➕' },
  { code: 'no_entry_sign', char: '🚫' },
  { code: 'ok', char: '🆗' },
  { code: 'new', char: '🆕' },
  { code: 'hourglass', char: '⏳' },
  { code: 'recycle', char: '♻️' },
  { code: 'red_circle', char: '🔴' },
  { code: 'green_circle', char: '🟢' },
  { code: 'blue_circle', char: '🔵' }
]
